set(PKG_CONFIG_FILE_CONTENT "${PKG_CONFIG_FILE_CONTENT}Name: zlib\n")
set(PKG_CONFIG_FILE_CONTENT "${PKG_CONFIG_FILE_CONTENT}Description: zlib compression library\n")
set(PKG_CONFIG_FILE_CONTENT "${PKG_CONFIG_FILE_CONTENT}Version: 1.2.11\n")
set(PKG_CONFIG_FILE_CONTENT "${PKG_CONFIG_FILE_CONTENT}Requires:\n")
set(PKG_CONFIG_FILE_CONTENT "${PKG_CONFIG_FILE_CONTENT}Libs: ${ZLIB_LIBRARY}\n")
set(PKG_CONFIG_FILE_CONTENT "${PKG_CONFIG_FILE_CONTENT}Cflags: -I${OUTPUT_DIR}\n")
message("GENERATING ZLIB PKG_CONFIG")

file(WRITE "${OUTPUT_DIR}/zlib.pc" "${PKG_CONFIG_FILE_CONTENT}")
