
file(STRINGS "${ffmpeg_BINARY_DIR}/Debug/ffbuild/config.mak" FFMPEG_CONFIG_MAK)
foreach(LINE IN LISTS FFMPEG_CONFIG_MAK)
  #message(${LINE})
  if("${LINE}" MATCHES "^CPPFLAGS=|^CFLAGS=")
    string(REGEX REPLACE "^CPPFLAGS= *" "" LINE "${LINE}")
    string(REGEX REPLACE "^CFLAGS= *" "" LINE "${LINE}")
    string(REGEX REPLACE " +" ";" LINE "${LINE}")
    string(REPLACE "$(SRC_PATH)" "${ffmpeg_SOURCE_DIR}" LINE "${LINE}")
    foreach(T IN LISTS LINE)
      set(RESPONSE_FILE "${RESPONSE_FILE}\n${T}")
    endforeach()
  endif()
endforeach()
message("RESPONSE_FILE")
message("${RESPONSE_FILE}")
message("ffmpeg_${CMAKE_BUILD_TYPE}.rsp" )
file(WRITE "ffmpeg_${CMAKE_BUILD_TYPE}.rsp" "${RESPONSE_FILE}")
