name: Build

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Git name 
      run: git config --global user.name "Github Actions"
    - name: Set Git email 
      run: git config --global user.email "no@email.com"
    - name: Prepare
      run: python prepare.py
    - name: nasm
      shell: cmd
      run: echo %PATH% && echo %USERPROFILE% && dir %USERPROFILE%\nasm-2.15.05  && where nasm
    - name: Version Bump
      run: python bump.py patch
    - name: Build
      shell: cmd
      run: call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat" && python -m build -n -w -Crelease
