name: Documentations

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: Thalamus
    - uses: actions/checkout@v4
      with:
        repository: cajigaslab/cajigaslab.github.io
        token: ${{ secrets.GH_PAGES_PAT }}
        path: cajigaslab
    - run: python3 -m pip install sphinx
    - run: sphinx-build -M html Thalamus/docs/source/ Thalamus/docs/build/
    - run: cp -r Thalamus/docs/build/html/* cajigaslab
    - run: git config --global user.email "no@email.com"
    - run: git config --global user.name "no name"
    - run: git add -A
      working-directory: cajigaslab
    - run: git commit -m "Update site"
      working-directory: cajigaslab
    - run: git push origin main
      working-directory: cajigaslab
