name: Documentations

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: git clone git@github.com:cajigaslab/cajigaslab.git
      working-directory: /home/runner/work
    - run: python3 -m pip install sphinx
    - run: sphinx-build -M html docs/source/ docs/build/
    - run: cp -r docs/build/html/* /home/runner/work/cajigaslab
    - run: git config --global user.email "no@email.com"
    - run: git config --global user.email "no name"
    - run: git add -A
      working-directory: /home/runner/work/cajigaslab
    - run: git commit -m "Update site"
      working-directory: /home/runner/work/cajigaslab
    - run: git push origin main
      working-directory: /home/runner/work/cajigaslab
