name: Documentation

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: Thalamus
    - uses: actions/checkout@v4
      with:
        ref: ghpages
        path: ghpages
    - run: python3 -m pip install sphinx
    - run: sphinx-build -M html Thalamus/docs/source/ Thalamus/docs/build/
    - run: cp -r Thalamus/docs/build/html/* ghpages
    - run: git config --global user.email "no@email.com"
    - run: git config --global user.name "no name"
    - run: git add -A
      working-directory: ghpages
    - run: git commit -m "Update site"
      working-directory: ghpages
    - run: git push origin ghpages
      working-directory: ghpages
