name: Build Linux

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - run: |
        if [ ! -d .git ]; then
          git init
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}:@github.com/$GITHUB_REPOSITORY
        else
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}:@github.com/$GITHUB_REPOSITORY
        fi
        git fetch origin $GITHUB_SHA
        git checkout $GITHUB_SHA
    - name: Version Bump
      run: source /py36/bin/activate && python bump.py patch
    - name: Build
      run: source /py36/bin/activate && python -m build -n -w -Crelease
    - name: Archive Distribution
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
