name: Build Linux

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Git name 
      run: git config --global user.name "Github Actions"
    - name: Set Git email 
      run: git config --global user.email "no@email.com"
    - name: Prepare
      run: python3 prepare.py
    - name: nasm
      run: echo $PATH && echo $HOME && ls $HOME/nasm-2.15.05  && which nasm
    - name: Version Bump
      run: python3 bump.py patch
    - name: Build
      run: python3 -m build -n -w -Crelease
