name: Build Linux

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: builder
    steps:
    - run: |
        if [ ! -d .git ]; then
          git init
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}:@github.com/$GITHUB_REPOSITORY
        else
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}:@github.com/$GITHUB_REPOSITORY
        fi
        git fetch origin $GITHUB_SHA
        git checkout $GITHUB_SHA
        git tag -d $(git tag -l)
    - name: Version Bump
      run: source /home/builder/.thalamusrc && source /py36/bin/activate && python bump.py patch
    - run: rm -rf dist && rm -rf /artifacts/dist
    - name: Build
      run: source /home/builder/.thalamusrc && echo PATH $PATH && source /py36/bin/activate && python -m build -n -w -Crelease
    - run: cp -r dist /artifacts
  upload:
    runs-on: uploader
    steps:
    - name: Archive Distribution
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: /artifacts/dist
       
