name: Build Linux

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - run: |
        if [ ! -d .git ]; then
          git init
          git remote add origin git@github.com:$GITHUB_REPOSITORY.git
        fi
        git fetch origin $GITHUB_SHA
        git checkout $GITHUB_SHA
    - name: Version Bump
      run: python3 bump.py patch
    - name: Build
      run: python3 -m build -n -w -Crelease
    - name: Archive Distribution
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
