name: Build Linux

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 1"
    
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Git name 
      run: git config --global user.name "Github Actions"
    - name: Set Git email 
      run: git config --global user.email "no@email.com"
    - name: Version Bump
      run: |
        python3 -m pip install toml
        python3 bump.py patch
    - run: |
        echo "#!/bin/bash" > prepare_and_build.sh
        echo "export DEBIAN_FRONTEND=noninteractive" >> prepare_and_build.sh
        echo "apt update" >> prepare_and_build.sh
        echo "apt install -y python3 python3-pip python3-venv curl sudo clang-10 libclang-10-dev git" >> prepare_and_build.sh
        echo "git config --global --add safe.directory '*'" >> prepare_and_build.sh
        echo "git log -1 --format=%h" >> prepare_and_build.sh
        echo "update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-10 100" >> prepare_and_build.sh
        echo "update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 100" >> prepare_and_build.sh
        echo "python3 -m venv pyenv" >> prepare_and_build.sh
        echo "source pyenv/bin/activate" >> prepare_and_build.sh
        echo "pip install -U pip setuptools" >> prepare_and_build.sh
        echo "python prepare.py" >> prepare_and_build.sh
        echo "source ~/.thalamusrc" >> prepare_and_build.sh
        echo "cmake --version" >> prepare_and_build.sh
        echo "python -m build -n -w -Crelease" >> prepare_and_build.sh
        chmod +x prepare_and_build.sh
        echo prepare_and_build.sh
        cat prepare_and_build.sh
        
    - name: Build
      uses: docker://ubuntu:18.04
      with:
        entrypoint: ./prepare_and_build.sh
    - name: Archive Distribution
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
    - run: git push
       
