name: Build Mac

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Git name 
      run: git config --global user.name "Github Actions"
    - name: Set Git email 
      run: git config --global user.email "no@email.com"
    - run: python3 -m venv pyenv
    - name: Prepare
      run: source pyenv/bin/activate && python3 prepare.py
    - name: nasm
      run: source $HOME/.thalamusrc && echo $PATH && echo $HOME && ls $HOME/nasm-2.15.05  && which nasm
    - name: Version Bump
      run: source $HOME/.thalamusrc && source pyenv/bin/activate && python3 bump.py patch
    - name: Build
      run: source $HOME/.thalamusrc && source pyenv/bin/activate && python3 -m build -n -w -Crelease
    - name: Archive Distribution
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
