name: Update devel-no-native

on:
  workflow_dispatch: {}
  push:
    branches:
      - devel
    
permissions:
  contents: write
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git config pull.rebase false
    - run: git fetch origin devel-no-native
    - run: git checkout devel-no-native
    - run: git pull origin devel
    - run: git push origin devel-no-native
